site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/morningstar-herro-java-03
edit_uri: https://github.com/harness-idp-sandbox/morningstar-herro-java-03/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core